### ISSUE TITLE
[Feature Request] Further reduce token cache access calls for apps that do not share cache

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1272]
**Is your feature request related to a problem? Please describe.**
Token cache access is expensive and should be reduced in frequency. After 4.2, we perform 2 cache accesses per call, i.e. `AcquireTokenSilent` and `AcquireTokenWithCertificate` will perform a read call (to see if there is smth in the cache) and a write call (if there's nothing in the cache, go to the network and save the results). 

**Describe the solution you'd like**
For applications that do not share the cache with other apps (be it with the same client ID or FOCI), the read call is superfluous. It would be sufficient to: 

- read the token cache in memory once at the beginning (i.e. after the user configures the token cache access delegates). Not sure about the API to do this.
- write the token cache from memory to disk  

This will eliminate up to 50% of the token cache access, as MSAL will only perform the write call, for example when removing accounts or when saving new tokens. 

**Impact**

- Most of our customers do not share the cache, so this modus operandi should be default. There should be a flag for enabling multi-app access. This would be a breaking change. 

Note that it is mostly web apps that are impacted by this, so another approach would be to have a flag for single-app cache access and set it from the Web extension library. 

-  Not sure about the API to perform the initial token cache read. Again, it could be made to live in the token cache implementation and exposed via extension libraries.

**Comment by jmprieur** [comment]
@bgavrilMS @pmaytak drawing your attention on this one which is about the performance of the cache.
This is probably already addressed by the last fix you proposed, @pmaytak. Can you please confirm?

**Comment by pmaytak** [comment]
@jmprieur I think the last fix partially addressed this - we reduced internal cache calls when no serialization cache is enabled. 
@bgavrilMS I think we touched on this in our previous discussions, but maybe we can discuss this more next week?

**Comment by bgavrilMS** [comment]
Well, in case of the singleton, the issue was solved by @pmaytak fix + customer partitioning the cache. 
In case of web site, this solution doesn't help much, because there would be 1 app per request anyway, so the read would happen.
