### ISSUE TITLE
[Bug] No client secret on web app - No specific error message

### ISSUE THREAD

**Issue by anasimao** [AzureAD/microsoft-authentication-library-for-dotnet#1576]
Facing an error where the no client secret was being used in a web app showed an error message that also mentioned a problem with Reply URL, only mentioning the client secret on the third line

A more precise error message should indicate that the error was with the client secret of the application.

REPRO:
On this specific case used the sample active-directory-aspnetcore-webapp-openidconnect-v2 and wanted to call an API (MS GRaph) to and did not change the client secret provided in the sample, so the value looked like this:
"ClientSecret": "[Copy the client secret added to the app from the Azure portal]"
After running the project, the page loads with the following error message:
MsalServiceException: The wrong application (public or confidential) is being used with this authentication flow. Potential issue: the redirect URI is valid, but it has been configured for the wrong app type. Check the configuration of the app being used in the app registration portal. See https://aka.ms/msal-net-invalid-client for details. Original exception: AADSTS7000215: Invalid client secret is provided.

**Comment by bgavrilMS** [comment]
I have already fixed that error message, which I agree is confusing. The "original exception" the useful bit. MSAL 4.8 will have the fix.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1556

**Comment by jmprieur** [comment]
Actually in that case (wrong client secret), the message won't work, or we need to add more to the aka.ms link.
We have more context here that we are in a confidential client app.

**Comment by jennyf19** [comment]
fixed in 4.8.1

**Comment by ChrisPetit** [comment]
This is still not fixed...I is not clear at all how to solve this error....

**Comment by jmprieur** [comment]
@anasimao : are you using the latest version of MSAL.NET? I see this error message all the time?
Is it an option for you to use Microsoft.Identity.Web ?

**Comment by bgavrilMS** [comment]
Please don't revive old issues without context. There is a form to fill for logging bugs, which should give us more insights, so please open a new issue and reference the old one if needed.
