### ISSUE TITLE
Unable to Sign in (Visual Studio)

### ISSUE THREAD

**Issue by amisett1969** [AzureAD/microsoft-authentication-library-for-dotnet#4914]
### Library version used

n/a

### .NET version

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.11.2

### Scenario

ManagedIdentityClient - managed identity

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Using: Microsoft Visual Studio Community 2022 (64-bit) - Current - Version 17.11.2
Cannot sign in getting the following error:
WAM Error  
 Error Code: 0 
 Error Message: Account has previously been signed out of this application. 
 Internal Error Code: 540940121 

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by ashok672** [comment]
The fix is currently being worked on. Will update the ETA for final release soon.

**Comment by Pasatedeverga** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b5177a41ae943c405d9b0554c2a4c237c3919335/src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs#L4

**Comment by DrCoolzic** [comment]
Exactly the same here:
WAM Error  
 Error Code: 0 
 Error Message: Account has previously been signed out of this application. 
 Internal Error Code: 540940121 

![image](https://github.com/user-attachments/assets/18d60203-4383-46fc-ab86-45012d9547be)

And ig I try "create feedback ticket" I cant log to developper community even if I have another tab already open with me logged in ???

**Comment by nl8322a** [comment]
Same here, still unable to push code from VS to my Azure Devops repo because I can't sign in

**Comment by ashok672** [comment]
The issue has been fixed with Microsoft.Identity.Client.NativeInterop package version 0.17.0

**Comment by DrCoolzic** [comment]
Still not working
![image](https://github.com/user-attachments/assets/ee55bab8-e076-4732-8b0d-19db4ff3787c)

using Microsoft Authenticator

**Comment by lgfx060223** [comment]
not working
using Microsoft Authenticator

liveshare account login is also not working

**Comment by markjercoates** [comment]
<img width="475" alt="Screenshot 2024-10-24 080031" src="https://github.com/user-attachments/assets/16b35ea8-9959-481f-bd4b-f213d227f8a7">

Yes I've go this error. have tried repairing my visual studio 2022 installation, restarting, deleting contents of my AppData, Local, .IdentityService directory and still can't sign in.
