### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by muhammetsahin** [AzureAD/microsoft-authentication-library-for-dotnet#570]
Hi,

I'm using Microsoft.Identity.Client, Version=1.1.3.-preview0012 

And i've got this error on iOS. (android works fine)

{System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Identity.Client.TokenCacheAccessor.Remove (System.String key, System.String service) [0x00055] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.TokenCacheAccessor.SetValueForKey (System.String key, System.String value, System.String service) [0x00000] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.TokenCacheAccessor.SaveAccessToken (System.String cacheKey, System.String item) [0x00000] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Telemetry.TelemetryTokenCacheAccessor.SaveAccessToken (System.String cacheKey, System.String item, Microsoft.Identity.Client.Internal.RequestContext requestContext) [0x00023] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.TokenCache.SaveAccessAndRefreshToken (Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters requestParams, Microsoft.Identity.Client.Internal.OAuth2.TokenResponse response) [0x00291] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache () [0x001a8] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.PostTokenRequest () [0x00008] in <7f73819fd99b45669100adda813d89e4>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__33.MoveNext () [0x00360] in <7f73819fd99b45669100adda813d89e4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at Microsoft.Identity.Client.PublicClientApplication+<AcquireTokenForUserCommonAsync>d__18.MoveNext () [0x000d2] in <7f73819fd99b45669100adda813d89e4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
…

**Comment by jennyf19** [comment]
@muhammetsahin Thank you so much for letting us know...was able to reproduce and will have a fix out shortly.

**Comment by jennyf19** [comment]
@muhammetsahin We have fixed this in [1.1.4-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/1.1.4-preview)


Manual testing done w/Android device, iOS device and iOS simulator

cc: @jmprieur @henrik-me

**Comment by muhammetsahin** [comment]
@jennyf19  thank you so much you are really fast.

**Comment by Journeyman42** [comment]
This issue is still in the latest versions - i was messing with this for an hour before rolling back all the way to version 1.1.2 preview 0008 when it just worked immediately. Why has the fix not been included in the updated versions?

**Comment by jennyf19** [comment]
@Journeyman42  This particular bug was not an issue for v2, as we moved the code to a common repository for refactoring, so I think you're running into a different issue. The format of the [cache between MSALv1 and v2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#you-can-now-enable-sso-between-adal-and-msal-apps-on-xamarinios) has changed, so now apps that run on iOS native msal can share cache with Xamarin .NET msal apps, so the way we access and use keychain has changed. 

Sounds like you've already spent some time on this, but if you want to double check the [keychain groups](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities#enable-keychain-groups) 
and try with Msalv2, we'd be interested in your results. Please open an issue in the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues) with your specific set-up and logs/stack trace.

**Comment by Journeyman42** [comment]
@jennyf19 Sorry, another question - I've just gone back through the link above checking everything again and one thing i noticed is the direction in AppDelegate to use SetBrokerContinuationEventArgs instead of SetAuthenticationContinuationEventArgs, only the former isn't available in the very latest version of Microsoft.Identity.Client?

**Comment by jennyf19** [comment]
@Journeyman42 - That is not correct. We do not have broker for MSAL yet. I will update the wiki. It should be:
```CSharp
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
{
        if (!AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(url))
        {
                return false;
        }
        return true;
}
```

Can you open an issue in MSAL with the logs and stack trace? this will help us investigate the issue you're running into. thanks.
