### ISSUE TITLE
MsalServiceException AADSTS50049 when targeting B2C

### ISSUE THREAD

**Issue by DaRosenberg** [AzureAD/microsoft-authentication-library-for-dotnet#632]
I just migrated our code to MSAL 2.2.0 and also changed to use the `b2clogin.com` domain instead of the `login.microsoft.com` domain we were using before.

I cannot seem to figure out how to construct the correct `authority` string. Here is what my code currently looks like:

```cs
private const string mTenant = "ideliverableb2c.onmicrosoft.com";
private const string mClientId = "d77e...caa6"; // Obfuscated here
private const string mSignInPolicyName = "B2C_1_si";

private PublicClientApplication mClientApplication =
    new PublicClientApplication(mClientId, authority: $"https://ideliverableb2c.b2clogin.com/tfp/{mTenant}/{mSignInPolicyName}")
    {
        RedirectUri = $"msal-{mClientId}://auth",
        ValidateAuthority = false
    };
```

I have tried various different ways to format the authority string, but no matter what I do I get the same exception when I call `mClientApplication.AcquireTokenAsync()`:

`Microsoft.Identity.Client.MsalServiceException: AADSTS50049: Unknown or invalid instance.`

Response body:

```json
{
    "error":"invalid_instance",
    "error_description":"AADSTS50049: Unknown or invalid instance.\r\nTrace ID: 6b61d006-7a2a-4b7e-b497-3cd6d9dc3800\r\nCorrelation ID: 78054f61-e0a9-4685-b761-64bc728ff90d\r\nTimestamp: 2018-10-09 19:28:23Z",
    "error_codes":[50049],
    "timestamp":"2018-10-09 19:28:23Z",
    "trace_id":"6b61d006-7a2a-4b7e-b497-3cd6d9dc3800",
    "correlation_id":"78054f61-e0a9-4685-b761-64bc728ff90d"
}
```

What am I doing wrong here?

**Comment by DaRosenberg** [comment]
@jennyf19 In response to your comments:

Yes, did read the docs. And yep, I'm aware that I'm formatting my redirect URI differently than the docs do, but I double checked to make sure that's not the issue.

I did some debugging by cloning your repo, and I think the problem might be here:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/core/src/Instance/AadInstanceDiscovery.cs#L99-L101

Because `ideliverableb2c.b2clogin.com` is not in the list of trusted hosts, the code falls back to the default trusted hosts, which is `login.microsoftonline.com` and as a result the HTTP error is returned by the first call to discover instances. Suspect this might be the issue?

**Comment by jennyf19** [comment]
@DaRosenberg Thanks 
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1314

**Comment by jennyf19** [comment]
@DaRosenberg I was able to repro this. Will meet w/B2C team tomorrow and get back to you. Thanks for bringing up this issue.

**Comment by jennyf19** [comment]
The instance discovery is not part of our client code, and needs to be fixed elsewhere. Still working on that...will update when we have meaningful information to share. 
@DaRosenberg

**Comment by jmprieur** [comment]
Added external until B2C adds a discovery endpoint

**Comment by AlexSchuetz** [comment]
Any informations on when b2clogin will be possible or on how to use it at the moment?

**Comment by mehamm** [comment]
Same issue as DaRosenberg above.  Not able to login using my-tenant-name.b2clogin.com as above but login.microsoftonline.com does work.  Tried multiple formats for the authority string but still continue to receive the following error: Microsoft.Identity.Client.MsalServiceException: AADSTS50049: Unknown or invalid instance.

One thing I did notice in my registered ad b2c app in the azure portal is that there is a default redirect URI  that is set to https://login.microsoftonline.com/tfp/oauth2/nativeclient that is not editable - not sure if this has anything to do with it

Is there a resolution to this problem or is it still ongoing?

Any help will be appreciated.

**Comment by tmarkovski** [comment]
Would be great to have this resolved in next release!

**Comment by jennyf19** [comment]
@DaRosenberg @AlexSchuetz @tmarkovski 
Fixed in latest release [Msal2.4.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.4.0).

**Comment by fileman** [comment]
Hi, even with 2.4.0-preview I got same exception.

I've used "ValidateAuthority = false" and the following:
- tenant.b2clogin.com/{Tenant}/
- tenant.b2clogin.com/tfp/{Tenant}/

other changes to code or b2c settings are required?

**Comment by tmarkovski** [comment]
@jennyf19 I can confirm the same as @fileman - still getting the same exception.

I tried every variation of URL
- https://[tenant_name].b2clogin.com/tfp/{Tenant_Guid}/{PolicySignUpSignIn}/v2.0/.well-known/openid-configuration
- https://[tenant_name].b2clogin.com/tfp/{Tenant_Guid}/{PolicySignUpSignIn}/v2.0/
- https://[tenant_name].b2clogin.com/tfp/{Tenant_Guid}/{PolicySignUpSignIn}/

With every combination of `ValidateAuthority`

**Comment by jennyf19** [comment]
@fileman @tmarkovski - thanks for the info. Will get back to you on this.

**Comment by jennyf19** [comment]
@fileman @tmarkovski @mixxit - Can you send me a fiddler trace and the tenant (jeferrie@microsoft.com)? Thanks.
Also, do you have the [identity providers](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-setup-fb-app) set up correctly?

**Comment by jennyf19** [comment]
@tmarkovski @fileman @mixxit Thanks for your patience while we sort this out. The issue is with the `GetAccountsAsync()` method, which is making a network call to the instance discovery endpoint. See this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/686). If this method runs before the AT call, then you'll get the eSTS exception you are seeing. We are working on a fix for this, as it impacts the cache, we need to coordinate with the other platforms before making changes, but this is high priority (as other customers have reported the need for `GetAccountsAsync()` to work offline) and we will hope to have a release out as soon as we can. 

I will keep you posted on the progress. Thanks again for reporting and your patience. 
cc: @jmprieur

**Comment by jennyf19** [comment]
@tmarkovski @fileman @mixxit updates are in dev, if you want to try it out. we will release with these changes very soon. thanks.

**Comment by jennyf19** [comment]
@DaRosenberg @tmarkovski @fileman @mixxit 
Fixed in [MSALv2.5.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.5.0)

**Comment by lybax** [comment]
It is also useful to specify that the Authority url should be like :

https://**TENANT**.b2clogin.com/**tfp**/**TENANT**.onmicrosoft.com/**POLICY**/v2.0/.well-known/openid-configuration

(never properly mentioned in any documentation)

**Comment by jmprieur** [comment]
@lybax actually no, the Authority URL should not have `/v2.0/.well-known/openid-configuration`
It should be https://TENANT.b2clogin.com/tfp/TENANT.onmicrosoft.com/POLICY

Do you think that we should make the following clearer: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#authority-for-a-b2c-tenant-and-policy ?

**Comment by lybax** [comment]
@jmprieur, you are right.
My mistake, I was in this case referring to the `OpenIdConnectAuthenticationOptions.MetadataAddress`, but in both case "tfp" seems to be mandatory.

**Comment by GammaFour** [comment]
**https://TENANT.b2clogin.com/tfp/TENANT.onmicrosoft.com/POLICY/v2.0/.well-known/openid-configuration**
This needs to be put in BIG, BOLD LETTERS on all the documentation and examples.  It took me a day to find this.  None of the old examples on GitHub work anymore with Azure B2C.  It wasn't until I used this new authority URL that I got my code, and the examples, to work.

**Comment by jennyf19** [comment]
@GammaFour  Which version of MSAL are you using?

**Comment by jmprieur** [comment]
and which sample @GammaFour ?

**Comment by worldspawn** [comment]
@jmprieur i'm trying to use this (https://github.com/Azure-Samples/ms-identity-javascript-v2) sample and can only get 50049. My authority uri is: `https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/tfp/B2C_1A_Samssignup_signin`. I can see the browser makes a request to `https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/tfp/b2c_1a_samssignup_signin/oauth2/v2.0/authorize`. The `authorization_endpoint` does not match match the _OAuth 2.0 authorization endpoint (v2)_ uri shown in the portal. In the portal theres no `tfp`.

**Comment by bgavrilMS** [comment]
Hi @worldspawn - this is the repo for MSAL .NET. Please open an issue on MSAL .js (https://github.com/AzureAD/microsoft-authentication-library-for-js) or directly on the sample.
