### ISSUE TITLE
MSAL v2.0+ on iOS failing even after making keychain changes

### ISSUE THREAD

**Issue by Journeyman42** [AzureAD/microsoft-authentication-library-for-dotnet#678]
---
name: Bug report
about: Create a report to help us improve

---

**Which Version of MSAL are you using ?**
2.3.1

**Which platform has the issue?**
Xamarin iOS

**What authentication flow has the issue?**

* Mobile
    * [ ] Xamarin.iOS

**What is the identity provider ?**

* [ ] Azure AD B2C

If B2C, what social identity did you use?
Email

**Repro**

I am using a clean Xamarin Forms project file
I implement the MSAL library LOWER than version 2.0
I implement the simplest possible interaction with MSAL (see code snippet below):
The app works as expected on iOS and Android, launching the login page
I update MSAL to any version higher than 2.0
I follow the instructions to add <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
I enable keychain access and specify com.microsoft.adalcache
I clean and rebuild the app
Now instead of launching the login page, the exception 'Object reference not set to an instance of an object' is triggered
Upgrading Android does not result in this error
I have also attempted to use a later version of MSAL 2.0 in at least two code samples on GitHub and both fail in similar ways even after making the keychain changes

```csharp
                    authenticationResult = await ADB2CClient.AcquireTokenAsync(
                      Constants.Scopes,
                    App.UiParent);
```

**Expected behavior**
iOS should still launch the login page.

**Actual behavior**
Object reference not set to an instance of an object'  

**Additional context/ Logs / Screenshots**

Callstack:

AuthTest.Authenticate.LoginPage.Handle_Clicked() in /Users/dbrickley/Projects/AuthTest/AuthTest/Authenticate/LoginPage.xaml.cs:31
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<AuthTest.Authenticate.LoginPage.<Handle_Clicked>d__4>(AuthTest.Authenticate.LoginPage stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84
AuthTest.Authenticate.LoginPage.Handle_Clicked(Xamarin.Forms.Button sender, System.EventArgs e) in 
Xamarin.Forms.Button.SendClicked() in D:/a/1/s/Xamarin.Forms.Core/Button.cs:133
Xamarin.Forms.Platform.iOS.ButtonRenderer.OnButtonTouchUpInside(UIKit.UIButton sender, System.EventArgs eventArgs) in 
UIKit.UIControlEventProxy.Activated() in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/UIKit/UIControl.cs:38
UIKit.UIApplication.UIApplicationMain() in 
UIKit.UIApplication.Main(string[] args, System.IntPtr principal, System.IntPtr delegate) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63
AuthTest.iOS.Application.Main(string[] args) in /Users/dbrickley/Projects/AuthTest/AuthTest.iOS/Main.cs:17

**Comment by jennyf19** [comment]
@Journeyman42 can you please provide msal logs?

**Comment by Journeyman42** [comment]
I've added logging and set to verbose but literally the only additional output I see is this one line preceding the error listed above

Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/07/2018 22:09:28] MSAL MSAL.Xamarin.iOS with assembly version '2.3.1.0', file version '2.3.1.0' and informational version '2.3.1-preview' is running...

**Comment by jennyf19** [comment]
@Journeyman42 Can you attach the logs or email them? Thanks. jeferrie@microsoft.com

**Comment by Journeyman42** [comment]
Not a bug, Jenny pointed out my error in not specifying UIParent in AppDelegate, I'd not thought it necessary as versions prior to 2.0 MSAL worked with that. thanks for the help

**Comment by jennyf19** [comment]
Thanks @Journeyman42  - glad it was a quick fix. Here's our documentation on the [UIParent for iOS](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#controlling-the-location-of-the-dialog-with-the-parent-parameters-uiparent) in case others stumble upon this issue as well.

**Comment by Journeyman42** [comment]
Jenny could you please try and give me a hand with another error I’m receiving on iOS, it’s only just started happening and cannot see what I’ve done to trigger it

the error is occurring after the user has entered login info and when trying to return the access token








Info (True) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:07 - b725e538-723c-421f-880a-9119f48e75e0] 
=== Request Data ===
Authority Provided? - True
Client Id - 6ec6ca7c-ff8d-4e52-8195-2b8d0439e88b
Scopes - https://alfretonb2c.onmicrosoft.com/api/user_impersonation
Redirect Uri - msal6ec6ca7c-ff8d-4e52-8195-2b8d0439e88b://auth
Validate Authority? - True
LoginHint provided? - False
User provided? - False
Extra Query Params Keys (space separated) - 
Slice Parameters Keys(space separated) - 

Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:07 - b725e538-723c-421f-880a-9119f48e75e0] Additional scopes - ;UIBehavior - select_account
Info (True) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:07 - b725e538-723c-421f-880a-9119f48e75e0] === Token Acquisition (InteractiveRequest) started:
	Authority: https://login.microsoftonline.com/tfp/alfretonb2c.onmicrosoft.com/b2c_1_userinfosignupsigninpolicy/
	Scope: https://alfretonb2c.onmicrosoft.com/api/user_impersonation
	ClientId: 6ec6ca7c-ff8d-4e52-8195-2b8d0439e88b
	Cache Provided: True
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:07 - b725e538-723c-421f-880a-9119f48e75e0] Resolving authority endpoints... Already resolved? - False
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:07 - b725e538-723c-421f-880a-9119f48e75e0] Is Authority tenantless? - False
Thread finished: <Thread Pool> #8
Thread started: <Thread Pool> #12
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:31 - b725e538-723c-421f-880a-9119f48e75e0] checking client info returned from the server..
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:31 - b725e538-723c-421f-880a-9119f48e75e0] Saving Token Response to cache..
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:31 - b725e538-723c-421f-880a-9119f48e75e0] Looking for scopes for the authority in the cache which intersect with https://alfretonb2c.onmicrosoft.com/api/user_impersonation
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:31 - b725e538-723c-421f-880a-9119f48e75e0] Intersecting scope entries count - 0
Info (False) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:31 - b725e538-723c-421f-880a-9119f48e75e0] Matching entries after filtering by user - 0
Error (True) MSAL 2.3.1.0 MSAL.Xamarin.iOS 12.1 [11/10/2018 13:04:31 - b725e538-723c-421f-880a-9119f48e75e0] System.ArgumentNullException: Value cannot be null.
Parameter name: str
  at Foundation.NSString..ctor (System.String str) [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/Foundation/NSString.cs:139 
  at Foundation.NSData.FromString (System.String s, Foundation.NSStringEncoding encoding) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/Foundation/NSData.cs:208 
  at Foundation.NSData.op_Implicit (System.String s) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/Foundation/NSData.cs:214 
  at Microsoft.Identity.Core.iOSTokenCacheAccessor.CreateRecord (System.String account, System.String service, System.String generic, System.Int32 type, System.String value) [0x00014] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Core.iOSTokenCacheAccessor.Save (System.String account, System.String service, System.String generic, System.Int32 type, System.String value) [0x00000] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Core.iOSTokenCacheAccessor.SaveAccount (Microsoft.Identity.Core.Cache.MsalAccountCacheItem item) [0x00033] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Core.Telemetry.TelemetryTokenCacheAccessor.SaveAccount (Microsoft.Identity.Core.Cache.MsalAccountCacheItem item) [0x00000] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Core.Telemetry.TelemetryTokenCacheAccessor.SaveAccount (Microsoft.Identity.Core.Cache.MsalAccountCacheItem item, Microsoft.Identity.Core.RequestContext requestContext) [0x0001f] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Client.TokenCache.SaveAccessAndRefreshToken (Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters requestParams, Microsoft.Identity.Core.OAuth2.MsalTokenResponse response) [0x00178] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.CacheTokenResponseAndCreateAuthenticationResult (Microsoft.Identity.Core.OAuth2.MsalTokenResponse msalTokenResponse) [0x00181] in <420cc22f37f340a0a560df4a374dbe4a>:0 
  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest+<ExecuteAsync>d__9.MoveNext () [0x00168] in <420cc22f37f340a0a560df4a374dbe4a>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase+<RunAsync>d__18.MoveNext () [0x000df] in <420cc22f37f340a0a560df4a374dbe4a>:0 
Debug: error in auth Value cannot be null.
Parameter name: str

**Comment by Journeyman42** [comment]
Unfortunately not

Ought it be possible to run ADAL and MSAL in the same project without conflicts? I appear to need the former in order to access the Graph API

**Comment by jennyf19** [comment]
@Journeyman42 Are you using a local B2C account for the login? 
What exactly do you need from ADAL
that you are not getting from MSAL? 
cc: @jmprieur

**Comment by Journeyman42** [comment]
Yes a local account. That’s why I used MSAL, so they can register email with AAD B2C.

Trouble is MSAL doesn’t allow you to read any aspect of their profile, so the token returned on login can’t give name, or email. 

that’s apparently why I need graph, and hence ADAL. It’d be much simpler if I could just get username etc via MSAL alone but I’ve seen no evidence you can and some that it’s just not possible.

**Comment by Journeyman42** [comment]
The info I had came from this page

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/526 <https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/526>

which links to this

https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet <https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet>

the thing is, it doesn’t seem right to expect a user to sign in first to graph and then to B2C just to get basic profile info

**Comment by Journeyman42** [comment]
When I build on device I get this

/Users/dbrickley/Projects/MicroliseMobile/MicroliseMobile.iOS/MTOUCH: Error MT4116: Could not register the assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory': error MT4118: Cannot register two managed types ('Microsoft.Identity.Core.UI.EmbeddedWebview.UniversalView, Microsoft.IdentityModel.Clients.ActiveDirectory' and 'Microsoft.Identity.Core.UI.EmbeddedWebview.UniversalView, Microsoft.Identity.Client') with the same native name ('UniversalView'). (MT4116) (MicroliseMobile.iOS)

Really annoying as this is the only way I can get it to work. It DOES work in the emulator.

I just want my users to sign up or sign in via MSAL / B2C and then to get hold of their user name so I can include it in calls made to API

Any advice, please?

**Comment by Journeyman42** [comment]
I came up with my own solution, tho I know it’s not perfect

I’ve removed ADAL from the Xamarin app but added the Nuget package to the secure API I’ve deployed to azure

Now I just get the session token via MSAL and make one call to the API containing the unique ID from the session token, the API takes that and with the client secret  returns the user name / profile info by making a call to graph

Seems to work fine. shame it’s necessary but its unblocked me.

**Comment by jmprieur** [comment]
Thanks @Journeyman42 
I still don't understand why you need ADAL to access Microsoft Graph. MSAL does it fine. Do you want to share a bit of code so that we see what can be improved?
(unless you are happy with your solution)

**Comment by bgavrilMS** [comment]
@jmprieur - aside, it is a good finding / P2 bug that ADAL and MSAL do not work toghter on iOS because they both try to register some obj-C classes with the same name. Possibly the same issue will be on Android...

**Comment by jmprieur** [comment]
@bgavrilMS : I agree. we overlooked this issue and need to fix it.

**Comment by Journeyman42** [comment]
well as I mentioned I got the info from this link (that it wasn’t possible or designed to work that way)

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/526 <https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/526>

I had a play around with some samples of ConfidentialClientApp to try and make use of the token I already had but failed to get it to work

**Comment by jmprieur** [comment]
@parakhj who should we work with to change this page to use MSAL.NET ?
 https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet

**Comment by SravanthiKare** [comment]
@jennyf19 
We are using ADB2C for login and ADAL AzureValut for fetching encryption key. We are getting below build error as both couldn't co-exist. Please suggest a way?

Could not register the assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory': error MT4118: Cannot register two managed types ('Microsoft.Identity.Core.UI.EmbeddedWebview.UniversalView, Microsoft.IdentityModel.Clients.ActiveDirectory' and 'Microsoft.Identity.Core.UI.EmbeddedWebview.UniversalView, Microsoft.Identity.Client') with the same native name ('UniversalView'). (MT4116)

**Comment by jennyf19** [comment]
@SravanthiKare missed your reply. This has been fixed. Please try the latest version of MSAL.
