### ISSUE TITLE
Azure DevOps iOS build fails with Microsoft.Idendity.Client

### ISSUE THREAD

**Issue by rkshnair** [AzureAD/microsoft-authentication-library-for-dotnet#852]
Version of lib - Microsoft.Idendity.Client 2.7.0
Platform - iOS
Build - Azure DevOps - Mac Agent.

**Background**
In our application the build get fails(in Azure DevOps) when we include **Microsoft.Idendity.Client** library for B2C authentication. I found many users reported the same issue, but nowhere I can find any solution for this issue. I am facing this issue from Dec 2018 and yet to find a solution.

**Exception I am getting**

>   MTOUCH : error MT2002: Failed to resolve "AuthenticationServices.ASWebAuthenticationSession" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

**I found this description in wiki page**

> Xamarin.iOS applications using the system web view now benefit from the integration with SFAuthenticationSession for iOS11 and ASWebAuthenticationSession for iOS12+

I doubt,
Azure Devops is using the cloud Mac Agent with some older version of Xamarin.iOS. But I don't know how to fix this issue.

I am facing lots of issues because of this.
> My gated build is failing. 
> I cannot distribute the app since the build is failing.

Please help

**Comment by rkshnair** [comment]
I managed to fix the issue with below script.
We need to execute this script before the build task. 
`- script: |
    echo "Setting mono version to 5_16_0_0"
    SYMLINK=5_16_0_0
    MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
    echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
    echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
    echo "Appending AppleSdkRoot to Settings.plist"
    mkdir -p /Users/vsts/Library/Preferences/Xamarin
    cd /Users/vsts/Library/Preferences/Xamarin
    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"https://www.apple.com/DTDs/PropertyList-1.0.dtd\">
    <plist version=\"1.0\">
    <dict>
    <key>AppleSdkRoot</key>
    <string>/Applications/Xcode_10.app</string>
    </dict>
    </plist>" >> Settings.plist
    echo "Setting Xcode version to 10.1 for Visual Studio for Mac"
    sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer
    sudo xcodebuild -showsdks
    sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0_0
`

And which is working for App Center & Azure Devops as well.

**Comment by jmprieur** [comment]
@trwalke fyi

**Comment by ramonesteban78** [comment]
I was able to make my Azure DevOps build works like @rkshnair indicated, but I have received this message from Apple once I uploaded the file to iTunes Connect :

SDK Version Issue - This app was built with the iOS 12.0 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

Any advice? I thought I was selecting xcode 10.1 with the previous script.
Thanks in advance

**Comment by jmprieur** [comment]
@trwalke : isn't this fixed in Azure DevOps now?

**Comment by trwalke** [comment]
@jmprieur the default version of the azure devops macOS hosted agent still does not have support for ASWebAuthenticationSession. Looks like we will need to run the script provided by @rkshnair.

**Comment by akamud** [comment]
The script @rkshnair posted is documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent

A more readable version of what I ended up using with success:

```sh
echo "Setting mono version to 5_16_0_0" 

sudo xcodebuild -showsdks

SYMLINK=5_16_0_0
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0_0
```

**Comment by bgavrilMS** [comment]
Should have been fixed by updating VS. Not an MSAL bug.
